70 create web button
NilFoundation/nil.foundation pull request #82
Opened 2023-10-27 14:31 UTC by Chipi007

#70

2023-10-27 16:45 UTC, ukorvl requested changes

2023-10-27 16:45 UTC, ukorvl commented on site/src/components/common/WebButton/WebButton.tsx
> +export default WebButton;
consider to run `npm run format:fix` to apply our format rules

2023-10-27 16:49 UTC, ukorvl requested changes

2023-10-27 16:49 UTC, ukorvl commented on site/src/components/common/WebButton/index.ts
> +export { default } from './WebButton';
prefer named export than default
`export {default as WebButton} from './WebButton`

2023-10-30 06:48 UTC, ukorvl approved these changes

2023-10-30 11:04 UTC, KlonD90 approved these changes

2023-10-30 11:14 UTC, merged